# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='markdown',
            field=models.BooleanField(default=False, verbose_name='Markdown:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=False, verbose_name='Markdown:'),
        ),
    ]
