# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161122_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='theUUID',
        ),
        migrations.RemoveField(
            model_name='squire',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='squire',
            name='theUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
