# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161122_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='theUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Private: Friends Only'), ('friends_of_friends', 'Private: Friends of Friends'), ('host_friends', 'Private: Friends on my Host Only'), ('only_me', 'Private: Me Only')], default='public', max_length=200, verbose_name='Privacy level of post:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.TextField(default='http://aedan.pythonanywhere.com/'),
        ),
    ]
