# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_theuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='theUUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
