# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161023_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('SQR', 'Squire'), ('SIR', 'Sir'), ('DME', 'Dame')], max_length=3)),
                ('first_name', models.CharField(max_length=200)),
                ('nation', models.CharField(choices=[('GDR', 'Gondor'), ('RHN', 'Rohan'), ('MDR', 'Mordor')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/static/img/default.png', upload_to='media'),
        ),
    ]
