# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161127_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Private: Friends Only'), ('FOAF', 'Private: Friends of Friends'), ('SERVERONLY', 'Private: Friends on my Host Only'), ('PRIVATE', 'Private: Me Only')], default='PUBLIC', max_length=200, verbose_name='Privacy level of post:'),
        ),
    ]
