# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161122_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='squire',
            name='hostname',
            field=models.TextField(default='SquireSpace', editable=False),
        ),
    ]
