# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161104_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('friends_of_friends', 'Friends of Friends'), ('host_friends', 'Friends on my Host Only'), ('another_author', 'Only ______'), ('only_me', 'Me Only')], default=('public', 'Public'), max_length=200, verbose_name='Privacy level of post:'),
        ),
    ]
