# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_squire_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SockPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('theUUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
