# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20161104_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_approve', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='post',
            name='otherauthor',
            field=models.CharField(choices=[('none', 'Default'), ('aedan', 'aedan'), ('dan', 'dan'), ('preyanshu', 'preyanshu'), ('dayna', 'dayna'), ('rishi', 'rishi'), ('John', 'John'), ('anyad', 'anyad'), ('usernamegreat', 'usernamegreat'), ('Sir_Edwaord_I', 'Sir_Edwaord_I'), ('user1', 'user1'), ('test1', 'test1'), ('test2', 'test2')], default=('none', 'Default'), max_length=200, verbose_name="Author post should be private to (if 'Private: Another Author' selected):"),
        ),
        migrations.AddField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Private: Friends Only'), ('friends_of_friends', 'Private: Friends of Friends'), ('host_friends', 'Private: Friends on my Host Only'), ('another_author', 'Private: Another Author'), ('only_me', 'Private: Me Only')], default=('public', 'Public'), max_length=200, verbose_name='Privacy level of post:'),
        ),
        migrations.AddField(
            model_name='squire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
