# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161118_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='otherauthor',
            field=models.CharField(choices=[('none', 'Default'), ('aedan', 'aedan'), ('dan', 'dan'), ('preyanshu', 'preyanshu'), ('dayna', 'dayna'), ('rishi', 'rishi'), ('John', 'John'), ('anyad', 'anyad'), ('usernamegreat', 'usernamegreat'), ('Sir_Edwaord_I', 'Sir_Edwaord_I'), ('user1', 'user1'), ('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3')], default=('none', 'Default'), max_length=200, verbose_name="Author post should be private to (if 'Private: Another Author' selected):"),
        ),
    ]
