# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_privatelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='otherauthor',
            field=models.CharField(choices=[('none', 'Default'), ('aedan', 'aedan'), ('dan', 'dan'), ('preyanshu', 'preyanshu'), ('dayna', 'dayna'), ('rishi', 'rishi'), ('John', 'John'), ('anyad', 'anyad'), ('usernamegreat', 'usernamegreat'), ('Sir_Edwaord_I', 'Sir_Edwaord_I'), ('user1', 'user1')], default=('none', 'Default'), max_length=200, verbose_name="Author post should be private to (if 'Private: Another Author' selected):"),
        ),
        migrations.AlterField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Private: Friends Only'), ('friends_of_friends', 'Private: Friends of Friends'), ('host_friends', 'Private: Friends on my Host Only'), ('another_author', 'Private: Another Author'), ('only_me', 'Private: Me Only')], default=('public', 'Public'), max_length=200, verbose_name='Privacy level of post:'),
        ),
    ]
