# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20161116_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_approve', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='post',
            name='otherauthor',
            field=models.CharField(choices=[('none', 'Default'), ('aedan', 'aedan'), ('dan', 'dan'), ('preyanshu', 'preyanshu'), ('dayna', 'dayna'), ('rishi', 'rishi'), ('John', 'John'), ('anyad', 'anyad'), ('usernamegreat', 'usernamegreat'), ('Sir_Edwaord_I', 'Sir_Edwaord_I'), ('user1', 'user1'), ('Anyad', 'Anyad'), ('tom', 'tom'), ('SuperSheep18', 'SuperSheep18'), ('supersheep18', 'supersheep18'), ('super', 'super'), ('supertriple', 'supertriple'), ('supe', 'supe'), ('supeaasdf', 'supeaasdf'), ('preyansh', 'preyansh'), ('fake', 'fake'), ('Preyansh', 'Preyansh')], default=('none', 'Default'), max_length=200, verbose_name="Author post should be private to (if 'Private: Another Author' selected):"),
        ),
        migrations.AddField(
            model_name='squire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
