# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161118_1413'),
        ('blog', '0009_auto_20161116_1647'),
    ]

    operations = [
    ]
