# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161120_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='otherauthor',
        ),
        migrations.AlterField(
            model_name='post',
            name='privatelevel',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Private: Friends Only'), ('friends_of_friends', 'Private: Friends of Friends'), ('host_friends', 'Private: Friends on my Host Only'), ('only_me', 'Private: Me Only')], default=('public', 'Public'), max_length=200, verbose_name='Privacy level of post:'),
        ),
    ]
