# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20161118_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squire',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='otherauthor',
            field=models.CharField(choices=[('none', 'Default'), ('aedan', 'aedan'), ('dan', 'dan'), ('preyanshu', 'preyanshu'), ('dayna', 'dayna'), ('rishi', 'rishi'), ('John', 'John'), ('anyad', 'anyad'), ('usernamegreat', 'usernamegreat'), ('Sir_Edwaord_I', 'Sir_Edwaord_I'), ('user1', 'user1'), ('Anyad', 'Anyad'), ('tom', 'tom')], default=('none', 'Default'), max_length=200, verbose_name="Author post should be private to (if 'Private: Another Author' selected):"),
        ),
        migrations.DeleteModel(
            name='Squire',
        ),
    ]
